global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using System.ComponentModel;
global using System.Globalization;
global using Core.Application;
global using Core.Domain;
global using ModelContextProtocol.Server;
global using NodaTime;